
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personnel
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-active: 10
      max-idle: 50
mybatis:
  mapper-locations: classpath:mapper/*.xml

